[project]
name = "ar-app"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12.3"

dependencies = [
  "django>=5.2.4",
  "psycopg2-binary>=2.9.10",
  "ruff>=0.12.4"
]

[project.optional-dependencies]
dev = ["python-decouple"]
